--
-- PostgreSQL database dump
--

\restrict RlusGBJTVFbFP79tM6uR1FdzmzpCuvdSvOEGvhX8odgrvpEJk4Hd4Ke49CteozJ

-- Dumped from database version 17.10 (Homebrew)
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: LegislationDocument; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."LegislationDocument" (id, slug, "titleRu", "titleUz", "titleEn", "summaryRu", "summaryUz", "summaryEn", "bodyRu", "bodyUz", "bodyEn", "sourceUrl", "sourceLabelRu", "sourceLabelUz", "sourceLabelEn", category, "publishedAt", "updatedAt", "createdAt", "editedAt") VALUES ('cmrq0aw790000x8k15do7lchh', 'law-on-science-and-scientific-activity', 'Закон «О науке и научной деятельности»', '“Ilm-fan va ilmiy faoliyat to‘g‘risida”gi Qonun', 'Law on Science and Scientific Activity', 'Базовый документ для понимания принципов научной деятельности, роли исследователей, организаций и государства.', 'Ilmiy faoliyat tamoyillari, tadqiqotchilar, tashkilotlar va davlatning roli bo‘yicha asosiy hujjat.', 'A core legal document explaining the principles of scientific activity and the roles of researchers, institutions, and the state.', '{"Этот документ помогает понять общие правовые основы науки, научных организаций, государственной поддержки и взаимодействия науки, образования и производства.","Для пользователя платформы это важный ориентир: он показывает, что при публикационной деятельности нужно учитывать не только требования журнала, но и общий нормативный контекст научной работы.","Финальную юридическую проверку всегда нужно выполнять по официальному тексту документа и актуальной редакции."}', '{"Ushbu hujjat ilm-fan, ilmiy tashkilotlar, davlat ko‘magi hamda fan, ta’lim va ishlab chiqarish o‘rtasidagi hamkorlikning umumiy huquqiy asoslarini tushunishga yordam beradi.","Platforma foydalanuvchisi uchun bu muhim yo‘riqnoma: u nashr jarayonida faqat jurnal talablarini emas, balki ilmiy faoliyatning umumiy me’yoriy kontekstini ham hisobga olish kerakligini ko‘rsatadi.","Yakuniy yuridik tekshiruv doimo hujjatning rasmiy matni va uning amaldagi tahriri asosida bajarilishi kerak."}', '{"This document outlines the general legal foundations of science, scientific organizations, state support, and the interaction between science, education, and industry.","For a platform user, this is an important reference point: publication work should be aligned not only with journal requirements but also with the broader regulatory framework of research activity.","Final legal verification should always be performed against the official text and the current version of the document."}', 'https://lex.uz/acts/4825305', 'Открыть документ на Lex.uz', 'Lex.uz da hujjatni ochish', 'Open the document on Lex.uz', 'science', '2020-10-29 00:00:00', '2024-01-10 00:00:00', '2026-07-18 06:49:22.053', '2026-07-18 06:49:22.053');
INSERT INTO public."LegislationDocument" (id, slug, "titleRu", "titleUz", "titleEn", "summaryRu", "summaryUz", "summaryEn", "bodyRu", "bodyUz", "bodyEn", "sourceUrl", "sourceLabelRu", "sourceLabelUz", "sourceLabelEn", category, "publishedAt", "updatedAt", "createdAt", "editedAt") VALUES ('cmrq0aw7m0001x8k16v1rsxrq', 'oak-official-sources-and-attestation-requirements', 'Официальные источники ВАК / OAK и требования к аттестации', 'OAK / VAK rasmiy manbalari va attestatsiya talablari', 'Official SAC/OAK sources and attestation requirements', 'Краткий навигатор по официальным ресурсам и проверке актуальных требований к научным степеням и аттестации.', 'Ilmiy darajalar va attestatsiya bo‘yicha amaldagi talablarni tekshirish uchun rasmiy manbalar bo‘yicha qisqa yo‘riqnoma.', 'A short guide to official resources and the verification of current requirements related to academic degrees and attestation.', '{"При работе с требованиями ВАК / OAK важно ориентироваться на официальные ресурсы уполномоченного органа, а не только на пересказы или рекламные материалы.","Пользователю следует проверять: действующие перечни, требования к публикациям, правила по специальностям, а также обновления, влияющие на диссертационные и аттестационные процедуры.","Платформа может служить удобной навигацией, но финальная верификация должна идти через официальный сайт и первоисточники."}', '{"OAK / VAK talablari bilan ishlashda faqat sharhlar yoki reklama materiallariga emas, balki vakolatli organning rasmiy resurslariga tayanish muhim.","Foydalanuvchi quyidagilarni tekshirishi kerak: amaldagi ro‘yxatlar, nashr talablari, ixtisosliklar bo‘yicha qoidalar va dissertatsiya hamda attestatsiya tartiblariga ta’sir qiluvchi yangilanishlar.","Platforma qulay yo‘riqnoma bo‘lishi mumkin, ammo yakuniy verifikatsiya rasmiy sayt va birlamchi manbalar orqali amalga oshirilishi kerak."}', '{"When working with SAC/OAK requirements, it is important to rely on the official resources of the authorized body rather than summaries or marketing materials alone.","Users should verify current lists, publication requirements, subject-specific rules, and updates that affect dissertation and attestation procedures.","The platform can serve as a convenient navigation layer, but final verification should always be done through the official website and primary sources."}', 'https://oak.uz/', 'Открыть официальный сайт OAK', 'OAK rasmiy saytini ochish', 'Open the official OAK website', 'attestation', '2024-03-15 00:00:00', '2025-02-01 00:00:00', '2026-07-18 06:49:22.067', '2026-07-18 06:49:22.067');
INSERT INTO public."LegislationDocument" (id, slug, "titleRu", "titleUz", "titleEn", "summaryRu", "summaryUz", "summaryEn", "bodyRu", "bodyUz", "bodyEn", "sourceUrl", "sourceLabelRu", "sourceLabelUz", "sourceLabelEn", category, "publishedAt", "updatedAt", "createdAt", "editedAt") VALUES ('cmrq0aw7p0002x8k11urlh97w', 'publication-ethics-and-plagiarism-check', 'Публикационная этика и проверка на плагиат', 'Nashr etikasi va plagiat tekshiruvi', 'Publication ethics and plagiarism checks', 'Справочный материал о том, почему редакционная этика, авторство и антиплагиат важны до подачи статьи.', 'Maqola yuborishdan oldin tahririy etika, mualliflik va antiplagiat nima uchun muhimligi haqida ma’lumot.', 'A reference note on why editorial ethics, authorship, and plagiarism checks matter before article submission.', '{"Перед подачей статьи автору важно проверить оригинальность текста, корректность авторства, корректность ссылок и соответствие редакционной политике журнала.","Даже если журнал не описывает все процедуры подробно, пользователю стоит ориентироваться на международные этические практики и официальные рекомендации профильных организаций.","Этот раздел платформы помогает сориентироваться, но не заменяет редакционную экспертизу и официальные требования конкретного издания."}', '{"Maqolani yuborishdan oldin muallif matnning originalligini, mualliflikning to‘g‘riligini, havolalarning aniqligini va jurnal tahririy siyosatiga mosligini tekshirishi muhim.","Agar jurnal barcha tartiblarni batafsil yozmagan bo‘lsa ham, foydalanuvchi xalqaro etik amaliyotlar va tegishli tashkilotlarning rasmiy tavsiyalariga tayanishi kerak.","Platformaning ushbu bo‘limi yo‘nalish beradi, ammo u tahririy ekspertiza va muayyan jurnalning rasmiy talablarini almashtirmaydi."}', '{"Before submitting an article, authors should verify originality, authorship accuracy, citation accuracy, and compliance with the journal’s editorial policy.","Even if a journal does not describe every procedure in detail, users should rely on international ethical practices and official guidance from relevant organizations.","This section of the platform is intended for orientation and does not replace editorial review or the official requirements of a specific journal."}', 'https://publicationethics.org/', 'Открыть COPE', 'COPE saytini ochish', 'Open COPE', 'ethics', '2025-01-20 00:00:00', '2025-05-15 00:00:00', '2026-07-18 06:49:22.07', '2026-07-18 06:49:22.07');


--
-- PostgreSQL database dump complete
--

\unrestrict RlusGBJTVFbFP79tM6uR1FdzmzpCuvdSvOEGvhX8odgrvpEJk4Hd4Ke49CteozJ

